language: ruby
rvm:
  - 2.4.1
sudo: false
cache: bundler
script:
  - bundle exec rake
  - bash <(curl -fsSL https://github.com/everypolitician/ensure-regression-tests/raw/v0.1.0/ensure-regression-tests)
